# png_to_vmu.R
#
# Converts a collection of PNG images to arrays of raw data that can be
# sent directly to a Dreamcast VMU LCD.
#
# Copyright (c) 2025 Colin Luoma

library(glue)
library(png)

# convert a sequence of binary digits to a decimal number
binary_to_decimal <- function(x) {
  char_vec <- as.character(x) |>
    strsplit("") |>
    unlist()
  char_vec <- (char_vec == 1) |>
    rev() |>
    which()
  char_vec <- char_vec - 1
  char_vec <- 2^char_vec |>
    sum()
  return(char_vec)
}

# read PNG file into a vector of bytes
# black/dark pixels get turned into a 1, otherwise 0
png_to_vmu_buffer <- function(filename) {
  img <- readPNG(filename)
  
  img_bw <- (img[,,1] + img[,,1] + img[,,1]) / 3
  img_bw <- apply(img_bw, c(1,2), FUN = \(x) {if(x < 0.3) 1L else 0L}, simplify = TRUE)
  img_bw <- c(t(img_bw))
  
  # create image buffer data
  img_buf <- NULL
  for (i in seq(1, length(img_bw), 8)) {
    img_buf <- c(img_buf, binary_to_decimal(img_bw[i:(i+7)]))
  }
  
  return(img_buf)
}

# convert a vector of bytes into a static C array
data_to_c_array <- function(array_name, data) {
  ar <- paste0("const uint8_t ", array_name, "[", length(data) + 8, "] = {\n\t")

  # First 2 bytes of a WRITE_BLOCK packet to send to the VMU LCD
  ar <- c(ar, "0x00, 0x00, 0x00, 0x04,\n\t")
  ar <- c(ar, "0x00, 0x00, 0x00, 0x00,\n\t")
  
  for (i in 1:(length(data)-1)) {
    ar <- c(
      ar,
      sprintf("0x%02X,", data[i])
    )
    if (i %% 6 == 0)
      ar <- c(ar, "\n\t")
  }
  ar <- c(ar, sprintf("0x%02X\n", data[length(data)]))
  
  ar <- c(ar, "};")
  
  return(paste0(ar, collapse = ""))
}

# create C source and header files containing the static arrays
write_to_c_files <- function(name, data) {
  
  append_to_c_file <- function(x) {
    write(x, file = paste0(name, ".c"), append = TRUE)
  }
  append_to_h_file <- function(x) {
    write(x, file = paste0(name, ".h"), append = TRUE)
  }
  
  # C
  write("", file = paste0(name, ".c"))
  append_to_c_file("// This file is autogenerated using png_to_vmu.R\n")
  append_to_c_file("#include <stdint.h>\n")
  for (buffer in data) {
    append_to_c_file(data_to_c_array(buffer$array_name, buffer$buf))
    append_to_c_file("")
  }
  
  # H
  write("", file = paste0(name, ".h"))
  append_to_h_file("// This file is autogenerated using png_to_vmu.R\n")
  append_to_h_file(glue("#ifndef {name}", name = paste0(toupper(name), "_H")))
  append_to_h_file(glue("#define {name}", name = paste0(toupper(name), "_H")))
  append_to_h_file("#include <stdint.h>\n")
  for (buffer in data) {
    append_to_h_file(paste0("extern const uint8_t ", buffer$array_name, "[", length(buffer$buf), "];"))
    append_to_h_file("")
  }
  append_to_h_file(glue("#endif // {name}", name = paste0(toupper(name), "_H")))
}

# add new images here
write_to_c_files(
  name = "dw_vmu_static_data",
  data = list(
    list(array_name = "vmu_static_dw_logo", buf = png_to_vmu_buffer("../images/logo_vmu.png"))
  )
)

# Move files to the project source directory
file.rename("dw_vmu_static_data.c", "../src/dw_vmu_static_data.c")
file.rename("dw_vmu_static_data.h", "../src/dw_vmu_static_data.h")