
// This file is autogenerated using png_to_vmu.R

#ifndef DW_VMU_STATIC_DATA_H
#define DW_VMU_STATIC_DATA_H
#include <stdint.h>

extern const uint8_t vmu_static_dw_logo[192];

#endif // DW_VMU_STATIC_DATA_H
